server:
  name: "FREE KEY"
  address: ":1211"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "resource/public"
  dumpRouterMap: true
  routeOverWrite: true
  jwtExpireDuration: "7D" # 7 days
  imgPrefix: "http://localhost:1211/upload/" # 图片前缀
  rootFilePath: "/resource/public/upload/"  # 文件上传路径
  rootIp: "localhost"
  rootPath: "/home/holw/learn/ciel-admin/"
  clientMaxBodySize: "200MB"

home: "/menu/path"

logger:
  path: "logs/default"
  level: "all"
  stdout: true

# 模板引擎配置
viewer:
  paths:
    - "resource/template"
# Database.
database:
  logger:
    level: "all"
    stdout: true
  default:
    link: "mysql:ciel:2zL4YEdLpLJirysN@tcp(127.0.0.1:3306)/ciel"
    debug: true
redis:
  default:
    address: "127.0.0.1:6379"
    db: 1
    pass: ""

# CLI.
gfcli:
  gen:
    dao:
      - link: "mysql:ciel:2zL4YEdLpLJirysN@tcp(127.0.0.1:3306)/ciel"
        tables: "s_admin,s_role,s_menu,s_role_menu,s_api,s_role_api,s_dict,s_file,s_operation_log,s_admin_login_log,
         f_node"
        removePrefix: "s_,f_"
        descriptionTag: true
        noModelComment: true
options:
  status: "1:正常:tag-info,2:禁用:tag-danger"
  api: "1:GET:tag-success,2:POST:tag-primary,3:PUT:tag-warning,4:DELETE:tag-danger"
  menuType: "1:菜单:tag-info,2:分组:tag-warning"
  dictGroup: "1:系统:tag-info,2:网站:tag-primary,3:备用:tag-warning,4:其他:tag-danger"
  dictType: "1:文本:tag-info,2:图片:tag-warning,3:富文本:tag-primary,4:文件:tag-danger,5:其他:tag-purple"
  fileGroup: "1:头像:tag-info,2:图片:tag-success,3:动图:tag-brown,4:音频:tag-warning,5:文件:tag-primary,6:其他:tag-danger"

